spring:
  application:
    name: dissertation-document-generator
  shell:
    interactive:
      enabled: true

logging:
  level:
    ru.ntoponen.dissertationdocumentgenerator: debug

dissertation:
  document:
    generator:
      settings:
        templates.folder: '/templates'
        dissertationBoard.url: 'https://www.rudn.ru/science/dissovet/dissertacionnye-sovety/pds-0200006'